package com.meshstream.core.model

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.Instant
import java.util.UUID

class VideoChunkTest {

    private fun makeChunk(
        status: ChunkStatus = ChunkStatus.PENDING,
        sha256Digest: ByteArray = ByteArray(32) { it.toByte() },
    ) = VideoChunk(
        id = UUID.randomUUID(),
        sessionId = UUID.randomUUID(),
        sequenceNumber = 0L,
        durationMs = 30_000L,
        createdAt = Instant.now(),
        sizeBytes = 1024L,
        sha256Digest = sha256Digest,
        keyHandle = "test-key-handle",
        status = status,
        hops = 0,
        originDeviceId = "device-123",
    )

    @Test
    fun `isForwardable returns true for PENDING status`() {
        val chunk = makeChunk(status = ChunkStatus.PENDING)
        assertTrue(chunk.isForwardable())
    }

    @Test
    fun `isForwardable returns true for QUEUED status`() {
        val chunk = makeChunk(status = ChunkStatus.QUEUED)
        assertTrue(chunk.isForwardable())
    }

    @Test
    fun `isForwardable returns false for IN_FLIGHT status`() {
        val chunk = makeChunk(status = ChunkStatus.IN_FLIGHT)
        assertFalse(chunk.isForwardable())
    }

    @Test
    fun `isForwardable returns false for DELIVERED status`() {
        val chunk = makeChunk(status = ChunkStatus.DELIVERED)
        assertFalse(chunk.isForwardable())
    }

    @Test
    fun `isForwardable returns false for DELETED status`() {
        val chunk = makeChunk(status = ChunkStatus.DELETED)
        assertFalse(chunk.isForwardable())
    }

    @Test
    fun `isForwardable returns false for FAILED status`() {
        val chunk = makeChunk(status = ChunkStatus.FAILED)
        assertFalse(chunk.isForwardable())
    }

    @Test
    fun `isDeletable returns true for DELIVERED status`() {
        val chunk = makeChunk(status = ChunkStatus.DELIVERED)
        assertTrue(chunk.isDeletable())
    }

    @Test
    fun `isDeletable returns false for PENDING status`() {
        val chunk = makeChunk(status = ChunkStatus.PENDING)
        assertFalse(chunk.isDeletable())
    }

    @Test
    fun `chunks with same id and digest are equal`() {
        val id = UUID.randomUUID()
        val sessionId = UUID.randomUUID()
        val digest = ByteArray(32) { 0xAB.toByte() }

        val chunk1 = VideoChunk(
            id = id,
            sessionId = sessionId,
            sequenceNumber = 1L,
            durationMs = 30_000L,
            createdAt = Instant.now(),
            sizeBytes = 512L,
            sha256Digest = digest,
            keyHandle = "key-1",
            status = ChunkStatus.PENDING,
            hops = 0,
            originDeviceId = "dev-1",
        )
        val chunk2 = chunk1.copy(status = ChunkStatus.DELIVERED, hops = 3)

        assertEquals(chunk1, chunk2)
    }

    @Test
    fun `chunks with different ids are not equal`() {
        val digest = ByteArray(32) { 0xAB.toByte() }
        val chunk1 = makeChunk(sha256Digest = digest)
        val chunk2 = makeChunk(sha256Digest = digest)
        // Different UUIDs are generated by makeChunk
        assertNotEquals(chunk1, chunk2)
    }

    @Test
    fun `copy preserves all fields except the one changed`() {
        val original = makeChunk(status = ChunkStatus.PENDING)
        val modified = original.copy(status = ChunkStatus.QUEUED)

        assertEquals(original.id, modified.id)
        assertEquals(original.sessionId, modified.sessionId)
        assertEquals(original.sequenceNumber, modified.sequenceNumber)
        assertEquals(ChunkStatus.QUEUED, modified.status)
    }

    @Test
    fun `default status is PENDING`() {
        val chunk = makeChunk()
        assertEquals(ChunkStatus.PENDING, chunk.status)
    }

    @Test
    fun `default hops is zero`() {
        val chunk = makeChunk()
        assertEquals(0, chunk.hops)
    }
}
